gfi_card_list:
    path:     /
    defaults: { _controller: GfiBundle:Card:list }

gfi_card_create:
    path:     /create
    defaults: { _controller: GfiBundle:Card:create }

gfi_card_edit:
    path:     /edit/{card}
    defaults: { _controller: GfiBundle:Card:edit }

gfi_card_view:
    path:     /view/{id}
    defaults: { _controller: GfiBundle:Card:view }

gfi_customer_list:
    path:     /customer
    defaults: { _controller: GfiBundle:Customer:list }

gfi_customer_create:
    path:     /customer/create
    defaults: { _controller: GfiBundle:Customer:create }

gfi_customer_contact_create:
    path:     /customer/{id}/contact/create
    defaults: { _controller: GfiBundle:CustomerContact:create }

gfi_customer_contact_edit:
    path:     /customer/contact/edit
    defaults: { _controller: GfiBundle:CustomerContact:edit }

gfi_customer_contact_list:
    path:     /customer/contact/list
    defaults: { _controller: GfiBundle:CustomerContact:list }

gfi_customer_edit:
    path:     /customer/edit/{id}
    defaults: { _controller: GfiBundle:Customer:edit }

gfi_customer_view:
    path:     /customer/view/{id}
    defaults: { _controller: Gfibundle:Customer:view }

gfi_admin_addUser:
    path:     /admin/addUser
    defaults: { _controller: GfiBundle:Admin:addUser }

gfi_admin_userList:
    path:     /admin/userList
    defaults: { _controller: GfiBundle:Admin:userList }

gfi_api_card_by_user_session:
    path:     /api/cardsByUserSession
    defaults: { _controller: GfiBundle:Api:cardsByUserSession }

gfi_api_card_by_user:
    path:     /api/cardsByUser/{id}
    defaults: { _controller: GfiBundle:Api:cardsByUser }

gfi_api_detail_card:
    path:     /api/customerCard/{id}
    defaults: { _controller: GfiBundle:Api:detailCard }

gfi_api_card_remove:
    path:     /api/customerCard/remove/{id}
    defaults: { _controller: GfiBundle:Api:removeCard}