gfi_index:
    path:     /
    defaults: { _controller: GfiBundle:Index:index }

gfi_admin_index:
    path:     /admin/
    defaults: { _controller: GfiBundle:Admin:adminIndex }

gfi_admin_addUser:
    path:     /admin/addUser
    defaults: { _controller: GfiBundle:Admin:addUser }
