<?php

namespace GfiBundle\Repository;

/**
 * ContactCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
