<?php

namespace GfiBundle\Repository;

/**
 * contact_customerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contact_customerRepository extends \Doctrine\ORM\EntityRepository
{
}
