<?php

namespace GfiBundle\Repository;
use GfiBundle\Entity\User;

/**
 * CustomerCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerCardRepository extends \Doctrine\ORM\EntityRepository
{
    public function cardsByUser(User $user)
    {
        $qb = $this->createQueryBuilder('c')
            ->join('c.users', 'u')
            ->where(':user = u.id')
            ->orderBy('c.id', 'DESC')
            ->setParameter('user', $user);
        
        return $qb->getQuery()->getResult();
    }
}
