<?php

namespace GfiBundle\Repository;

/**
 * CustomerCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerCardRepository extends \Doctrine\ORM\EntityRepository
{
}
