<?php

namespace GfiBundle\Repository;

/**
 * customer_cardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class customer_cardRepository extends \Doctrine\ORM\EntityRepository
{
}
